import { useEffect, useState } from 'react';
import Card from '../components/Card.jsx';
import { api } from '../services/api.js';
import BettingModeControl from '../components/BettingModeControl.jsx';

export default function ShadowMode() {
  const [status, setStatus] = useState(null); const [trades, setTrades] = useState([]); const [error, setError] = useState(null);
  async function refresh() { try { const [s,t] = await Promise.all([api.get('/api/shadow/status'), api.get('/api/shadow/trades')]); setStatus(s.data.status); setTrades(t.data.trades || []); } catch (e) { setError(e.message); } }
  useEffect(() => { refresh(); const id = setInterval(refresh, 3000); return () => clearInterval(id); }, []);
  async function action(name) { try { await api.post(`/api/shadow/${name}`, name === 'start' ? { starting_balance: 5000, goal_balance: 10000, profile: 'PROFILE_A' } : {}); await refresh(); } catch (e) { setError(e?.response?.data?.error || e.message); } }
  return <div className="space-y-5"><BettingModeControl /><div><h1 className="text-3xl font-semibold">Shadow Mode</h1><p className="mt-1 text-sm text-zinc-400">MODE: SHADOW · PAPER BETS · NOT REAL · no live browser execution or live ledger writes.</p></div>{error && <div className="rounded border border-rose-500/40 p-3 text-sm text-rose-200">{error}</div>}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Mode',status?.mode],['Balance',status?.current_balance],['Goal',status?.goal_balance],['P/L',status?.profit],['Bets',status?.bets],['Wins',status?.wins],['Losses',status?.losses],['ROI',status?.roi == null ? 'UNKNOWN' : `${(status.roi * 100).toFixed(1)}%`]].map(([k,v]) => <Card key={k}><div className="text-xs uppercase text-zinc-500">{k}</div><div className="mt-1 text-xl font-semibold">{v == null ? 'UNKNOWN' : v}</div></Card>)}</section><Card title="Shadow controls"><div className="flex gap-2"><button onClick={() => action('start')} className="rounded bg-emerald-600 px-3 py-2 text-sm">Start Shadow</button><button onClick={() => action('pause')} className="rounded bg-amber-600 px-3 py-2 text-sm">Pause</button><button onClick={() => action('resume')} className="rounded bg-sky-600 px-3 py-2 text-sm">Resume</button><button onClick={() => action('stop')} className="rounded bg-zinc-700 px-3 py-2 text-sm">Stop</button></div></Card><Card title="Paper trades"><div className="space-y-2">{trades.map(t => <div key={t.execution_id} className="grid grid-cols-5 rounded bg-zinc-900 p-2 text-xs"><span>{t.target_round_id}</span><span>{t.status}</span><span>{t.result || 'PENDING'}</span><span>{t.pnl ?? 'UNKNOWN'}</span><span>SIMULATED</span></div>)}</div></Card></div>;
}
