import { useEffect, useState } from 'react';
import Card from '../components/Card.jsx';
import { api } from '../services/api.js';

export default function StrategyResearch() {
  const [runs, setRuns] = useState([]); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(null);
  async function refresh() { try { const { data } = await api.get('/api/research'); setRuns(data.runs || []); if (!selected && data.runs?.[0]) setSelected(data.runs[0]); } catch (e) { setError(e.message); } }
  useEffect(() => { refresh(); }, []);
  async function run() { setBusy(true); setError(null); try { const { data } = await api.post('/api/research/run', { profile: '', mode: 'SIMULATION' }); setSelected(data.result); await refresh(); } catch (e) { setError(e?.response?.data?.detail || e.message); } finally { setBusy(false); } }
  const r = selected; const selectedConfig = r?.selected?.config || {}; const test = r?.final_untouched_test || {};
  return <div className="space-y-5"><div><h1 className="text-3xl font-semibold">Strategy Research</h1><p className="mt-1 text-sm text-zinc-400">Historical simulation research only. Candidates are selected on validation; the final test remains untouched.</p></div>{error && <div className="rounded border border-rose-500/40 p-3 text-sm text-rose-200">{error}</div>}<Card title="Experiments"><button disabled={busy} onClick={run} className="rounded bg-emerald-600 px-4 py-2 text-sm">{busy ? 'Running…' : 'Run research'}</button><span className="ml-3 text-xs text-zinc-500">Default mode: SIMULATION · production configuration is never changed</span></Card>
    {r && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Research ID',r.research_id],['Selected profile',selectedConfig.profile || 'ROBUST RANGE'],['Threshold range',(r.robustness?.stable_range || []).join(', ') || 'UNKNOWN'],['Untouched test P/L',test.pnl ?? 'UNKNOWN'],['Untouched test bets',test.bets ?? 'UNKNOWN'],['Overfitting',r.overfitting?.detected ? 'DETECTED' : 'NOT DETECTED'],['Train score',r.overfitting?.train_score],['Validation score',r.overfitting?.validation_score]].map(([k,v]) => <Card key={k}><div className="text-xs uppercase text-zinc-500">{k}</div><div className="mt-1 text-lg font-semibold">{v == null || v === '' ? 'UNKNOWN' : v}</div></Card>)}</section><Card title="Candidate configurations"><div className="max-h-72 overflow-auto text-xs">{(r.candidates || []).map(c => <div key={`${c.config.profile}-${c.config.probability_threshold}`} className="grid grid-cols-5 border-b border-zinc-800 py-2"><span>{c.config.profile}</span><span>{c.config.probability_threshold}</span><span>{c.validation?.pnl ?? 'UNKNOWN'}</span><span>{c.validation?.bets ?? 0} bets</span><span>{c.score?.toFixed?.(2) ?? c.score}</span></div>)}</div></Card><Card title="Sensitivity / robustness"><div className="space-y-1 text-sm">{(r.sensitivity || []).map(s => <div key={s.value}>Threshold {s.value}: validation P/L {s.validation?.pnl ?? 'UNKNOWN'}, test P/L {s.test?.pnl ?? 'UNKNOWN'}</div>)}<p className="mt-3 text-xs text-zinc-500">{r.overfitting?.note}</p></div></Card></>}</div>;
}
